# Generated by Django 2.2.7 on 2020-04-07 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('campaign', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.FloatField()),
                ('number_of_seats', models.IntegerField()),
                ('locations_were_unchanged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=250, null=True)),
                ('accepted_by_driver', models.BooleanField(default=False)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_end_location', to='location.Location')),
                ('inside_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to='campaign.Campaign')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_passenger', to=settings.AUTH_USER_MODEL)),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_start_location', to='location.Location')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='transport.Transport')),
            ],
        ),
    ]
