# Generated by Django 2.2.7 on 2020-05-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='locations_were_unchanged',
        ),
    ]
