# Generated by Django 2.2.7 on 2020-04-07 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_is_negotiable', models.BooleanField(default=False)),
                ('time_is_negotiable', models.BooleanField(default=True)),
                ('price_is_negotiable', models.BooleanField(default=True)),
                ('number_of_seats_are_negotiable', models.BooleanField(default=True)),
                ('start_location_is_negotiable', models.BooleanField(default=True)),
                ('end_location_is_negotiable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.FloatField()),
                ('number_of_seats', models.IntegerField()),
                ('passengers_were_found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=250, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_location', to='location.Location')),
                ('negotiability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiability', to='transport.Negotiability')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_location', to='location.Location')),
            ],
        ),
    ]
