# Generated by Django 2.2.7 on 2020-04-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
